### ISSUE TITLE
console.log在哪显示

### ISSUE THREAD

**Issue by shangxin2533** [alibaba/Thera#10]
![5f2620a9-78f3-4ff1-9a01-7bfeb2596415](https://cloud.githubusercontent.com/assets/13247402/23840070/356cd092-07dd-11e7-9daa-a7b209f82614.png)
在we文件里写了console.log("11");请问log在哪里显示呢。

**Comment by kekemao1** [comment]
get,是一个bug @778477

**Comment by 778477** [comment]
感谢反馈。

weex模板中的日志，可在`logcat`tab下查看。 该版本的模拟器还未接入weex-tool inspector协议。我们近日会提供一个新版本

**Comment by shangxin2533** [comment]
没看懂，你的意思是以后会在logcat选项卡中看到，目前有问题看不到是吗

**Comment by 778477** [comment]
是的。

**Comment by 778477** [comment]
@shangxin2533  
https://github.com/alibaba/Thera/releases/tag/v0.4.12-beta 已经支持查看模板`console.log`打印出来的日志

**Comment by shangxin2533** [comment]
![8849b059-8807-4b83-a784-41e2a11e69b3](https://cloud.githubusercontent.com/assets/13247402/23892038/fb17d034-08d3-11e7-8dcc-1b0492353a53.png)
打不开

**Comment by 778477** [comment]
不好意思，这个包的签名有点问题。
新版本的mac os不允许运行未被认可的开发者提供的app。
我们会重新发包。
