### ISSUE TITLE
tex & label 里 font-size 小数点精准太大了

### ISSUE THREAD

**Issue by kekemao1** [alibaba/Thera#21]
![default](https://cloud.githubusercontent.com/assets/530631/25032367/1be43f10-2106-11e7-93b6-ec7b4aef5e7a.png)

**Comment by 778477** [comment]
这个可以定个规范：取小数点后几位，向上取整或向下取整。

**Comment by kekemao1** [comment]
我觉得基本上好像都是int形，但不能肯定int是否满足需求或有没有问题，可以试试。因为留小数点是没必要的

**Comment by 778477** [comment]
iOS Preview 已做ceil 向上取整处理
