### ISSUE TITLE
Cmd+Q should kill the whole process tree.

### ISSUE THREAD

**Issue by dutlxq2014** [alibaba/Thera#32]
We modify the strategy of starting the dumpling server which boots up immediately with thera.
When restart thera after Cmd+Q, the available PORT for dumpling server always change to a new one which leads to the failure of auto connection. This may confuse users. Is there any solution to the kill operation ?

**Comment by NickolasHu** [comment]
send 'SIGINIT' to child process before quit. [code](https://github.com/TheraPackages/weex-run/commit/fa42049e51db889ccb86308c7b28dc81c9928076#diff-8f6a48b2b6bdac27aa911abc0985f80bR24)
