### ISSUE TITLE
为什么生成的还是we结尾的呢？不是开始vue的了吗

### ISSUE THREAD

**Issue by zuijiaoluo** [alibaba/Thera#4]
![image](https://cloud.githubusercontent.com/assets/22735208/23575886/7c3997b2-00d0-11e7-9230-867bc2461fd7.png)

**Comment by kekemao1** [comment]
config等部分菜单目前没有做完，当前版本是beta.3月底会支持到。
vue我们正在支持中，目前涉及到对vue语言的编译环节如高亮、提醒等功能还需要很大的工作量，所以我们优先解决.we
我们还需要些时间。
