### ISSUE TITLE
.js文件是生成文件不能编辑的

### ISSUE THREAD

**Issue by scucheri** [alibaba/Thera#45]
.js文件是生成文件不能编辑的，当用户错误的去编辑js文件而不是we或者vue文件的时候，应该给出友好提示，否则容易以为是bug，修改了内容一直无法正常同步给链接的设备

**Comment by 778477** [comment]
由dumpling 导出的js文件，在末尾有注释代码：

```
/* auto created by dumplings server with weex-devtool 2017-05-09 15:10:46 */
```

**Comment by kekemao1** [comment]
我也遇到这个问题，建议是采用更强的提醒！

**Comment by NickolasHu** [comment]
trasnform后面可以放在thera中做, 把transform完成的js发给dumpling.
因为前端有框架, rax等定制, 和build工具定制需求. thera可以把这些口子开放出来.
这样js也可以做编辑.

**Comment by 778477** [comment]
ok

**Comment by dutlxq2014** [comment]
![image](https://cloud.githubusercontent.com/assets/8983445/26295851/a020ef38-3efe-11e7-8b22-670a546e553a.png)

Android Stuidio 不能编辑的提示可以这样

**Comment by dutlxq2014** [comment]
Optimization has done @All. Building process has been moved to [builder-plugin-weex](https://github.com/TheraPackages/builder-plugin-weex) package. More detail please refer to this issue: [#56](https://github.com/alibaba/Thera/issues/56).
