### ISSUE TITLE
Panel activation event hides right panel.

### ISSUE THREAD

**Issue by NickolasHu** [alibaba/Thera#55]
### Description

In file symbols-tree-view.coffee

```coffeescript
    attached: ->
      @onChangeEditor = atom.workspace.onDidChangeActivePaneItem (editor) =>
        @removeEventForEditor()
        @populate()
```

### Steps to Reproduce

1. Open right panel.
2. Click text editor.
3. Click tree view.

**Expected behavior:** [What you expect to happen]

Right panel always visible.

**Actual behavior:** [What actually happens]

Right panel appears and then disappears.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always.

### Versions

You can get this information from copy and pasting the output of `thera --version ` from the command line. Also, please include the OS and what version of the OS you're running.

Thera 0.6.1-dev

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dengxu** [comment]
ok~

**Comment by dengxu** [comment]
ok 已经修复
