### ISSUE TITLE
Build service optimization

### ISSUE THREAD

**Issue by dutlxq2014** [alibaba/Thera#56]
### Description

1. 由Tree监听所有文件的变化并发送通知，接收者识别文件名称做操作

    command name: `thera-project-service:file-changed`
message type `{event: event, filePath: filePath}`, event type reference [chokidar](https://github.com/paulmillr/chokidar)

2. 项目配置内容通过service的方式提供

build configuration

```

"build": {
    "apply": "debug",
    "types": {
      "debug": {
        "minify": false,
        "sourcemap": false
      },
      "release": {
        "minify": false,
        "sourcemap": false
      },
    }
  }
```

3. 监听到*.vue/launch.json发生变更时（需要检查主文件），需要重新build并发送到app
4. 编辑输出目录的.js文件时，也需要更新通知到app（需要检查主文件）
5. 通过菜单选项也可以进行build操作
6. 由build-service包负责推送编译后的js内容

builder service config：

```
"providedServices": {
    "thera-builder-service": {
      "description": "Build server for weex.",
      "versions": {
        "1.0.0": "provideBuildService"
      }
    }
  }
```

**Comment by NickolasHu** [comment]
Here is how to use project config service. `weex-run ~1.1.38`

Add consumedServices in package.json
```
  "consumedServices": {
    "thera-project-config": {
      "description": "Consume project config object",
      "versions": {
        "1.0.0": "cosumeProjectConfig"
      }
    }
  }
```

The project service will read project configuration in real time, and return a promise object.

```  
  cosumeProjectConfig (configurationManager) {
    configurationManager.getConfig().then((c) => console.log(c))
  }
```

**Comment by dutlxq2014** [comment]
* [x] 由Tree监听所有文件的变化并发送通知，接收者识别文件名称做操作;
* [x] 项目配置内容通过service的方式提供;
* [x] 监听到*.vue/launch.json发生变更时（需要检查主文件），需要重新build并发送到app;
* [x] 编辑输出目录的.js文件时，也需要更新通知到app（需要检查主文件）;
* [x] 通过菜单选项也可以进行build操作; implemented in builder package.
* [x] 由build-service包负责推送编译后的js内容;
