### ISSUE TITLE
Symbol tab style issue.

### ISSUE THREAD

**Issue by NickolasHu** [alibaba/Thera#63]
### Description

Symbol tab style issue.

### Steps to Reproduce

1. Start preview
2. press debug button
3. press symbol tab

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

thera 0.6.4-dev.3

You can get this information from copy and pasting the output of `thera --version ` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by NickolasHu** [comment]
Seems like the same issue with https://github.com/alibaba/Thera/issues/64.
Never show again.

**Comment by dengxu** [comment]
The issue has fixed on symbol-tree-view v0.13.19
