### ISSUE TITLE
mac 模拟器不显示

### ISSUE THREAD

**Issue by shangxin2533** [alibaba/Thera#9]
![7830e8a3-ab23-4a5f-97aa-7fb9076b0d0b](https://cloud.githubusercontent.com/assets/13247402/23816975/d264de26-062a-11e7-9e27-2f1dbc96b373.png)

打开IDE后选择虚拟设备的下拉框就一个选项general device，Xcode已经安装了，是什么原因，我的电脑是16款pro

**Comment by kekemao1** [comment]
Xcode安装完毕后，请保证 模拟器能够RUN一次，因为刚安装完毕后，苹果有很多协议还需要你CHECK。所以请用XCODE保证模拟器能够运行一次，再用THERA启动模拟器

**Comment by shangxin2533** [comment]
![de0200cb-0c3d-488d-9b88-db8e1f7476fa](https://cloud.githubusercontent.com/assets/13247402/23822178/0bce1694-0682-11e7-9551-1c5fbbfe036e.png)
模拟器可以运行，但thera还是不显示模拟器

**Comment by 778477** [comment]
感谢反馈。

你可以在 命令行中键入 ` xcrun simctl list -j ` 将结果copy到这里看一下吗？

另外可以尝试重启Thera 或者 reload window，查看模拟器列表功能是否正常。

**Comment by kekemao1** [comment]
请问一下，你的XCODE是从APPSTORE直接下载的？还是其他地方下载安装包，自己安装的？@shangxin2533

**Comment by shangxin2533** [comment]
好了，可以了，只需要执行一个命令就行：
sudo xcode-select -switch  /Applications/Xcode.app/Contents/Developer
，多谢大家
